apiVersion: v1
kind: Secret
metadata:
  # versioned, cadence independent of app version
  name: cka-secrets-v1
  labels:
      app.kubernetes.io/name: circonus-kubernetes-agent
stringData:
  ## Circonus API Key is REQUIRED
  circonus-api-key: {{ .Values.circonus_api_key | quote }}
  ## For in-cluster operation, the service account token
  ## will be used. Only set this to use a DIFFERENT token 
  ## than the kubernetes-bearer-token-file setting
  ## below. The file will always take precedence, ensure 
  ## kubernetes-bearer-token-file is set to "" when using 
  ## this setting.
  #kubernetes-bearer-token: ""