workspaces:
  - name: "121"
    proxy:
      port: 8121
    vars:
      - name: kubernetes_version
        value: "1.21"
    kubectl:
      context: gke_circonus-dev_us-central1_manual-1-21-k8s-agent-e2e-zonal-cluster
  - name: "122"
    proxy:
      port: 8122
    vars:
      - name: kubernetes_version
        value: "1.22"
    kubectl:
      context: gke_circonus-dev_us-central1_manual-1-22-k8s-agent-e2e-zonal-cluster
  - name: "123"
    proxy:
      port: 8123
    vars:
      - name: kubernetes_version
        value: "1.23"
    kubectl:
      context: gke_circonus-dev_us-central1_manual-1-23-k8s-agent-e2e-zonal-cluster
  - name: "124"
    proxy:
      port: 8124
    vars:
      - name: kubernetes_version
        value: "1.24"
    kubectl:
      context: gke_circonus-dev_us-central1_manual-1-24-k8s-agent-e2e-zonal-cluster
  - name: "125"
    proxy:
      port: 8125
    vars:
      - name: kubernetes_version
        value: "1.25"
    kubectl:
      context: gke_circonus-dev_us-central1_manual-1-25-k8s-agent-e2e-zonal-cluster
