project_name: circonus-kubernetes-agent

before:
  hooks:
    - go mod tidy
    - cmd: golangci-lint run
      env:
        - GOOS=linux
    - govulncheck ./...

builds: 
  - id: cka
    main: main.go
    binary: sbin/circonus-kubernetes-agentd
    env: 
      - CGO_ENABLED=0
    goarch: 
      - amd64
      - arm64
    goos: 
      - linux
    ignore: 
      - 
        goarch: 386
    flags:
      - -trimpath
    ldflags: 
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.VERSION={{.Version}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.COMMIT={{.ShortCommit}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.DATE={{.Date}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.TAG={{.Tag}}

dockers: 
  - id: cka-amd64
    goos: linux
    goarch: amd64
    goarm: ""
    ids: ['cka']
    build_flag_templates: 
      - "--pull"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: docker/x86_64/Dockerfile
    image_templates: 
      - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
      - "circonus/{{.ProjectName}}:latest-amd64"
    skip_push: false

  - id: cka-arm64
    goos: linux
    goarch: arm64
    goarm: ""
    ids: ['cka']
    build_flag_templates: 
      - "--pull"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    dockerfile: docker/arm64/Dockerfile
    image_templates: 
      - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
      - "circonus/{{.ProjectName}}:latest-arm64"
    skip_push: false

docker_manifests: 
  - name_template: "circonus/{{.ProjectName}}:latest"
    image_templates: 
      - "circonus/{{.ProjectName}}:latest-amd64"
      - "circonus/{{.ProjectName}}:latest-arm64"
    
  - name_template: "circonus/{{.ProjectName}}:{{.Tag}}"
    image_templates: 
      - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
      - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
    
archives: 
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    files: 
      - LICENSE
      - README.md
      - CHANGELOG.md

release: 
  draft: false
  github: 
    name: circonus-kubernetes-agent
    owner: circonus-labs
  prerelease: auto

checksum: 
  name_template: "{{.ProjectName}}_checksums.txt"

sboms:
  - artifacts: archive
    args: ["$artifact", "--output", "cyclonedx-json@1.5=$document"]
    env:
      - SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES=true
      - SYFT_GOLANG_SEARCH_REMOTE_LICENSES=true

after:
  hooks:
    - cmd: bash -c 'for b in *.sbom; do grype -q --add-cpes-if-none $b; done'
      dir: ./dist