---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: circonus-kubernetes-agent
    labels:
      app.kubernetes.io/name: circonus-kubernetes-agent
      app.kubernetes.io/version: latest
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: circonus-kubernetes-agent
        app.kubernetes.io/version: latest
    replicas: 1
    template:
      metadata:
        name: circonus-kubernetes-agent
        labels:
          app.kubernetes.io/name: circonus-kubernetes-agent
          app.kubernetes.io/version: latest
      spec:
        serviceAccountName: circonus-kubernetes-agent
        containers:
          - name: circonus-kubernetes-agent
            image: circonuslabs/circonus-kubernetes-agent:latest
            ## for ARM64, remove line above and uncomment line below
            #image: circonuslabs/circonus-kubernetes-agent-arm64:latest
            command: ["/circonus-kubernetes-agentd"]
            env:
              - name: CKA_CIRCONUS_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: cka-secrets-v1
                    key: circonus-api-key
              - name: CKA_K8S_NAME
                valueFrom:
                  configMapKeyRef:
                    name: cka-config-v1
                    key: kubernetes-name
              - name: GODEBUG
                value: "madvdontneed=1"
            livenessProbe:
              httpGet:
                path: /health
                port: 8080                
              initialDelaySeconds: 30
            volumeMounts:
              - name: configs
                mountPath: /ck8sa
                readOnly: true
        volumes:
          - name: configs
            configMap:
              name: cka-config-v1
              items:
                - key: default-alerts.json
                  path: default-alerts.json