##
## NOTE: Required attributes must be set:
##       1. circonus-api-key
##       2. kubernetes-name
##
---
    apiVersion: v1
    kind: Secret
    metadata:
      # versioned, cadence independent of app version
      name: cka-secrets-v1
      labels:
          app.kubernetes.io/name: circonus-kubernetes-agent
    stringData:
      ## REQUIRED -- Circonus API Key
      circonus-api-key: ""

---
  apiVersion: v1
  kind: ConfigMap
  metadata:
      # versioned, cadence independent of app version
      name: cka-config-v1
      labels:
          app.kubernetes.io/name: circonus-kubernetes-agent
  data:
      ## REQUIRED -- name identifying the cluster, used in the check 
      ## title and check target when check is created (so agent can find
      ## the check again when pod is re-deployed) also used in various
      ## tags on rules, contact group, etc.
      kubernetes-name: ""
      ##
      ## alert configuration
      ##
      ## REQUIRED -- contact.email (if not supplied, alerting and some dashboard functionality will be disabled)
      ##
      default-alerts.json: |
        {
          "contact": {
            "email": ""
          },
          "rule_settings": { 
            "crashloops_container": {
              "threshold": "0",
              "window": 300
            },
            "crashloops_init_container": {
              "threshold": "0",
              "window": 300
            },
            "cpu_utilization": {
              "threshold": "75",
              "window": 900
            },
            "disk_pressure": {
              "threshold": "0",
              "window": 300
            },
            "memory_pressure": {
              "threshold": "0",
              "window": 300
            },
            "pid_pressure": {
              "threshold": "0",
              "window": 300
            },
            "network_unavailable": {
              "threshold": "0",
              "window": 300
            },
            "job_failures": {
              "threshold": "0",
              "window": 300
            },
            "persistent_volume_failures": {
              "threshold": "0",
              "window": 300
            },
            "pod_pending_delays": {
              "threshold": "0.99",
              "window": 900
            },
            "deployment_glitches": {
              "min_threshold": "0",
              "min_window": 300,
              "max_threshold": "0",
              "max_window": 300
            },
            "daemonsets_not_ready": {
              "min_threshold": "0",
              "min_window": 300,
              "max_threshold": "0",
              "max_window": 300
            },
            "statefulsets_not_ready": {
              "min_threshold": "0",
              "min_window": 300,
              "max_threshold": "0",
              "max_window": 300
            },
          }
        }
