repositories:
- name: prometheus-community
  url: "https://prometheus-community.github.io/helm-charts"

releases:
  - name: kube-state-metrics
    namespace: kube-system
    chart: prometheus-community/kube-state-metrics
