repositories:
- name: metrics-server
  url: "https://kubernetes-sigs.github.io/metrics-server/"

releases:
  - name: metrics-server
    installed: false
    namespace: kube-system
    chart: metrics-server/metrics-server
