releases:
- name: circonus-kubernetes-agent
  namespace: circonus-kubernetes-agent
  chart: ../../../contrib/helm/
  values:
  - ../config/{{`{{ .Release.Name }}`}}/values.yaml
  - kubernetes_name: {{ requiredEnv "CLUSTER_NAME" }}
  - image: {{ requiredEnv "REGISTRY_NAME" }}/circonus-kubernetes-agent:latest
  secrets:
  - ../config/{{`{{ .Release.Name }}`}}/secrets.yaml
