releases:
- name: circonus-kubernetes-agent
  namespace: circonus-kubernetes-agent
  chart: ../../../../contrib/helm/
  values:
  - ../config/{{`{{ .Release.Name }}`}}/values.yaml
  secrets:
  - ../config/{{`{{ .Release.Name }}`}}/secrets.yaml
