## WARN: this is a template rendered from a file in $reporoot/templates/files/
circonus_api_key: ""
kubernetes_name: ""
contact_email: ""
broker_cid: "/broker/35"
dns:
  port: "10055"
metric_filters: |
  {
    "metric_filters": [
      ["allow", "^.+$", "tags", "and(collector:dynamic)", "NO_LOCAL_FILTER dynamically collected metrics"],
      ["allow", "^(Disk|Memory|PID)Pressure$", "node status"],
      ["allow", "^(container|node|pod)_.*$", "node metrics k8s v1.18+"],
      ["allow", "^(kube_)?pod_container_status_(running|terminated|waiting|ready)(_count)?$", "containers"],
      ["allow", "^(kube_)?pod_container_status_(terminated|waiting)_reason(_count)?$", "containers health"],
      ["allow", "^(kube_)?pod_init_container_status_(terminated|waiting)_reason(_count)?$", "init containers health"],
      ["allow", "^(kube_)?pod_status_(ready|scheduled)(_count)?$", "tags", "and(condition:true)", "pods"],
      ["allow", "^(kube_)?pod_status_phase(_count)?$", "tags", "and(or(phase:Running,phase:Pending,phase:Failed,phase:Succeeded))", "pods"],
      ["allow", "^(node|kubelet_running_pod_count|Ready)$", "nodes"],
      ["allow", "^(pod|node)_cpu_usage_seconds_total$", "utilization"],
      ["allow", "^(pod|node)_memory_working_set_bytes$", "utilization"],
      ["allow", "^(used|capacity)$", "tags", "and(or(units:bytes,units:percent),or(resource:memory,resource:fs,volume_name:*),not(container_name:*),not(sys_container:*))", "utilization"],
      ["allow", "^NetworkUnavailable$", "node status"],
      ["allow", "^[rt]x$", "tags", "and(resource:network,or(units:bytes,units:errors),not(container_name:*),not(sys_container:*))", "utilization"],
      ["allow", "^apiserver_request_total$", "tags", "and(or(code:5*,code:4*))", "api req errors"],
      ["allow", "^authenticated_user_requests$", "api auth"],
      ["allow", "^authentication_attempts$", "api auth health"],
      ["allow", "^cadvisor.*$", "cadvisor"],
      ["allow", "^capacity_.*$", "node capacity"],
      ["allow", "^collect_.*$", "agent collection stats"],
      ["allow", "^coredns*", "dns health"],
      ["allow", "^coredns_(dns|forward)_request_(count_total|duration_seconds_avg)$", "dns health"],
      ["allow", "^coredns_(dns|forward)_response_rcode_count_total$", "dns health"],
      ["allow", "^daemonset_scheduled_delta$", "health"],
      ["allow", "^deployment_generation_delta$", "health"],
      ["allow", "^events$", "events"],
      ["allow", "^kube_(service_labels|deployment_labels|pod_container_info|pod_deleted)$", "ksm inventory"],
      ["allow", "^kube_(service|deployment)_labels$", "ksm inventory"],
      ["allow", "^kube_daemonset_status_(current|desired)_number_scheduled$", "health"],
      ["allow", "^kube_deployment_(created|spec_replicas)$", "deployments"],
      ["allow", "^kube_deployment_(metadata|status_observed)_generation$", "health"],
      ["allow", "^kube_deployment_status_(replicas|replicas_updated|replicas_available|replicas_unavailable)$", "deployments"],
      ["allow", "^kube_deployment_status_replicas_unavailable$", "deployments"],
      ["allow", "^kube_hpa_(spec_max|status_current)_replicas$", "scale"],
      ["allow", "^kube_job_status_failed$", "health"],
      ["allow", "^kube_namespace_status_phase$", "namespaces"],
      ["allow", "^kube_namespace_status_phase$", "tags", "and(or(phase:Active,phase:Terminating))", "namespaces"],
      ["allow", "^kube_node_spec_unschedulable$", "node status"],
      ["allow", "^kube_node_status_allocatable$", "node status"],
      ["allow", "^kube_node_status_condition$", "node status health"],
      ["allow", "^kube_persistentvolume_status_phase$", "health"],
      ["allow", "^kube_pod_info$", "pods"],
      ["allow", "^kube_pod_start_time$", "pods"],
      ["allow", "^kube_pod_status_condition$", "pods"],
      ["allow", "^kube_statefulset_status_(replicas|replicas_ready)$", "health"],
      ["allow", "^kubedns*","dns health"],
      ["allow", "^kubelet_.*$", "node metrics k8s v1.18+"],
      ["allow", "^machine_.*$", "node metrics k8s v1.18+"],
      ["allow", "^pod_container_status$", "containers"],
      ["allow", "^pod_container_status_(terminated|waiting)_reason(_count)?$", "containers health"],
      ["allow", "^pod_init_container_status_(terminated|waiting)_reason(_count)?$", "init containers health"],
      ["allow", "^pod_status_(ready|scheduled)$", "pods"],
      ["allow", "^pod_status_phase$", "pods"],
      ["allow", "^prober_.*$", "node metrics/probes k8s v1.18+"],
      ["allow", "^resource_(request|limit)$", "resources"],
      ["allow", "^statefulset_replica_delta$", "health"],
      ["allow", "^usage(Milli|Nano)Cores$", "tags", "and(not(container_name:*),not(sys_container:*))", "utilization"],
      ["allow", "^utilization$", "utilization health"],
      ["deny", "^.+$", "all other metrics"]
    ]
  }
  